"""Initial migration - clientes and productos tables

Revision ID: 56a081a46bbd
Revises: 
Create Date: 2025-06-29 18:20:23.851177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a081a46bbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('nif_cif', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cliente_user_email', 'clientes', ['user_id', 'email'], unique=False)
    op.create_index('idx_cliente_user_id', 'clientes', ['user_id'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_user_id'), 'clientes', ['user_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_iva', sa.String(length=10), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_producto_user_codigo', 'productos', ['user_id', 'codigo'], unique=False)
    op.create_index('idx_producto_user_id', 'productos', ['user_id'], unique=False)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_user_id'), 'productos', ['user_id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('iva_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_factura_user_cliente', 'facturas', ['user_id', 'cliente_id'], unique=False)
    op.create_index('idx_factura_user_id', 'facturas', ['user_id'], unique=False)
    op.create_index('idx_factura_user_numero', 'facturas', ['user_id', 'numero'], unique=False)
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    op.create_index(op.f('ix_facturas_user_id'), 'facturas', ['user_id'], unique=False)
    op.create_table('lineas_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_iva', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_linea_factura_id', 'lineas_factura', ['factura_id'], unique=False)
    op.create_index(op.f('ix_lineas_factura_id'), 'lineas_factura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineas_factura_id'), table_name='lineas_factura')
    op.drop_index('idx_linea_factura_id', table_name='lineas_factura')
    op.drop_table('lineas_factura')
    op.drop_index(op.f('ix_facturas_user_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_index('idx_factura_user_numero', table_name='facturas')
    op.drop_index('idx_factura_user_id', table_name='facturas')
    op.drop_index('idx_factura_user_cliente', table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_productos_user_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index('idx_producto_user_id', table_name='productos')
    op.drop_index('idx_producto_user_codigo', table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_clientes_user_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index('idx_cliente_user_id', table_name='clientes')
    op.drop_index('idx_cliente_user_email', table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
